name: Dermatology Arts
favicon: null
layout_spectrum: 0.58067
typography_spectrum: 0.16048
title: Dermatology practice Drs. Samir Master and Casey Carlos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#95c361'
    - '#82857e'
    - '#eff5e7'
    - '#9ea09b'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
