name: Dermatology Arts
favicon: null
layout_spectrum: 0.32269
typography_spectrum: 0.16048
title: Website of Drs. Samir Master and Casey Carlos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a3d39'
    - '#748f47'
    - '#455f3e'
    - '#10130e'
    - '#c9d1b7'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
