name: Dermatology Arts
favicon: null
layout_spectrum: 0.7367574218660593
typography_spectrum: 0.8127711531706154
title: Dermatology Arts Home Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acc5b5'
    - '#889485'
    - '#334900'
    - '#161a02'
    - '#8a9d1c'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.1700576776638627
purpose: []
