name: Dermatology Arts
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13287
title: Dermatology Arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#152727'
    - '#2a4033'
    - '#4b5e48'
    - '#74805e'
    - '#859470'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
